'use client'

import { useState } from 'react'

const CATEGORIES = ['Marketing','Sales','Finance','HR','Operations','Customer Support','Content','Data Management','Other']
const TRIGGERS = [
  { icon: '📧', label: 'New email received' },
  { icon: '📝', label: 'Form submitted' },
  { icon: '📊', label: 'New spreadsheet row' },
  { icon: '⏰', label: 'Scheduled time' },
  { icon: '🔗', label: 'Webhook from app' },
  { icon: '📁', label: 'File uploaded' },
  { icon: '📅', label: 'Calendar event' },
  { icon: '🖱️', label: 'Manual trigger' },
]
const TOOLS = ['Gmail','Notion','Slack','Airtable','HubSpot','Shopify','Google Sheets','Calendly','Trello','ClickUp','Stripe','Typeform']
const OUTCOMES = ['Send notification','Update spreadsheet','Create task','Send email','Post to Slack','Create CRM record','Generate report','Upload file']
const STEP_LABELS = ['Describe your problem','Choose your trigger','Select your tools','Define your outcome','Final details']
const LOADING_STEPS = ['Analyzing your use case','Selecting n8n nodes','Wiring connections','Adding error handling','Finalizing JSON']

export default function GeneratePage() {
  const [step, setStep] = useState(1)
  const [credits, setCredits] = useState(4)
  const [status, setStatus] = useState<'form'|'loading'|'success'>('form')
  const [loadingStep, setLoadingStep] = useState(0)

  // Form state
  const [problem, setProblem] = useState('')
  const [category, setCategory] = useState('')
  const [trigger, setTrigger] = useState('')
  const [tools, setTools] = useState<string[]>([])
  const [outcome, setOutcome] = useState('')
  const [outcomes, setOutcomes] = useState<string[]>([])
  const [constraints, setConstraints] = useState('')
  const [email, setEmail] = useState('')
  const [emailError, setEmailError] = useState(false)
  const [generatedJSON, setGeneratedJSON] = useState('')

  const toggleTool = (tool: string) =>
    setTools(prev => prev.includes(tool) ? prev.filter(t => t !== tool) : [...prev, tool])

  const toggleOutcome = (o: string) =>
    setOutcomes(prev => prev.includes(o) ? prev.filter(x => x !== o) : [...prev, o])

  const progress = (step / 5) * 100

  const buildPICF = () => `Build a production-ready n8n workflow for this exact use case:

WHAT NEEDS TO BE AUTOMATED:
${problem}

DETAILS:
- Category: ${category || 'General business process'}
- Trigger: ${trigger || 'Manual trigger'}  
- Apps/tools to connect: ${tools.length > 0 ? tools.join(', ') : 'Use appropriate n8n native nodes'}
- What should happen at the end: ${outcome || 'Complete the automation successfully'}
- Additional actions needed: ${outcomes.length > 0 ? outcomes.join(', ') : 'None'}
- Edge cases and constraints: ${constraints || 'Handle errors gracefully'}

Build a complete, professional workflow with proper error handling, descriptive node names, and a Setup Checklist sticky note listing all credentials needed.`

  const sampleJSON = () => JSON.stringify({
    name: (category || 'My') + ' Automation Workflow',
    nodes: [
      { id: 'node-001', name: trigger || 'Webhook Trigger', type: 'n8n-nodes-base.webhook', typeVersion: 1, position: [250, 300], parameters: { httpMethod: 'POST', path: 'workflow-trigger' } },
      { id: 'node-002', name: 'Process Data', type: 'n8n-nodes-base.set', typeVersion: 3, position: [500, 300], parameters: {} },
      { id: 'node-003', name: 'Send Confirmation', type: 'n8n-nodes-base.gmail', typeVersion: 2, position: [750, 300], parameters: { toEmail: '={{ $json.email }}', subject: 'Automation triggered!' } }
    ],
    connections: {
      [trigger || 'Webhook Trigger']: { main: [[{ node: 'Process Data', type: 'main', index: 0 }]] },
      'Process Data': { main: [[{ node: 'Send Confirmation', type: 'main', index: 0 }]] }
    },
    settings: { executionOrder: 'v1' },
    meta: { description: problem ? problem.substring(0, 80) + '...' : 'Generated by PromptToFlow' }
  }, null, 2)

const generate = async () => {
    if (!email || !email.includes('@')) { setEmailError(true); return }
    setEmailError(false)
    sessionStorage.setItem('ptf_form_data', JSON.stringify({
      problem, category, trigger, tools, outcome, outcomes, constraints, email, credits
    }))
    window.location.href = '/review'
  }
    setLoadingStep(0)

    const interval = setInterval(() => {
      setLoadingStep(prev => {
        if (prev >= 4) { clearInterval(interval); return prev }
        return prev + 1
      })
    }, 700)

    try {
      const controller = new AbortController()
      const timeout = setTimeout(() => controller.abort(), 55000)
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: buildPICF(), email }),
        signal: controller.signal
      })
      clearTimeout(timeout)
      const data = await res.json()
      clearInterval(interval)
      if (!data.workflow) {
        throw new Error(data.error || 'No workflow returned')
      }
      setGeneratedJSON(JSON.stringify(data.workflow, null, 2))
      if (data.toolsUsed) sessionStorage.setItem('ptf_tools_used', JSON.stringify(data.toolsUsed))
} catch (err) {
      clearInterval(interval)
      console.error('Generation error:', err)
      setStatus('form')
      alert('Something went wrong. Please try again.')
      return
    }

    setCredits(c => Math.max(0, c - 1))
    setTimeout(() => setStatus('success'), 200)
  }

  const download = () => {
    const blob = new Blob([generatedJSON], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'prompttoflow-workflow.json'; a.click()
    URL.revokeObjectURL(url)
    setTimeout(() => { window.location.href = '/setup-guide' }, 1000)
  }

  return (
    <div style={{ fontFamily: "'Cabinet Grotesk', sans-serif", background: '#080C14', minHeight: '100vh', display: 'flex', flexDirection: 'column', color: '#F0F4FF' }}>

      {/* NAV */}
      <nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 40px', borderBottom: '1px solid #1F2D45', background: '#0D1320', position: 'sticky', top: 0, zIndex: 100 }}>
        <div style={{ fontWeight: 900, fontSize: 18, letterSpacing: -0.5 }}>Prompt<span style={{ color: '#00D4FF' }}>To</span>Flow</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: 'rgba(200,241,53,0.1)', border: '1px solid rgba(200,241,53,0.2)', padding: '6px 14px', borderRadius: 99, fontFamily: 'monospace', fontSize: 12, color: '#A8D020' }}>
          <div style={{ width: 7, height: 7, borderRadius: '50%', background: '#C8F135' }} />
          {credits} credits remaining
        </div>
      </nav>

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '48px 20px 80px' }}>

        {/* PROGRESS */}
        {status === 'form' && (
          <div style={{ width: '100%', maxWidth: 680, marginBottom: 40 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 12 }}>
              <span style={{ fontSize: 13, color: '#8B9ABF' }}>{STEP_LABELS[step - 1]}</span>
              <span style={{ fontFamily: 'monospace', fontSize: 12, color: '#4A5A7A' }}>Step 0{step} / 05</span>
            </div>
            <div style={{ height: 4, background: '#1A2438', borderRadius: 99, overflow: 'hidden' }}>
              <div style={{ height: '100%', width: progress + '%', background: '#00D4FF', borderRadius: 99, transition: 'width 0.5s ease' }} />
            </div>
            <div style={{ display: 'flex', gap: 6, marginTop: 10 }}>
              {[1,2,3,4,5].map(i => (
                <div key={i} style={{ flex: 1, height: 3, borderRadius: 99, background: i < step ? '#00D4FF' : i === step ? 'rgba(0,212,255,0.5)' : '#1A2438', transition: 'background 0.3s' }} />
              ))}
            </div>
          </div>
        )}

        {/* FORM CARD */}
        <div style={{ width: '100%', maxWidth: 680, background: '#111827', border: '1px solid #1F2D45', borderRadius: 16, overflow: 'hidden' }}>

          {/* STEP 1 */}
          {status === 'form' && step === 1 && (
            <div style={{ padding: 40 }}>
              <div style={{ fontFamily: 'monospace', fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', color: '#00D4FF', marginBottom: 12 }}>Step 01 — The Problem</div>
              <h2 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -0.8, lineHeight: 1.15, marginBottom: 8 }}>What are you doing<br />manually right now?</h2>
              <p style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 32, lineHeight: 1.6 }}>Describe the repetitive task that's eating your time.</p>
              <textarea value={problem} onChange={e => setProblem(e.target.value)} placeholder="e.g. Every time I get a new lead, I manually copy their details into HubSpot, send a welcome email, and create a follow-up task in Notion..." style={{ width: '100%', background: '#1A2438', border: '1px solid #263348', borderRadius: 8, padding: '14px 16px', fontSize: 14, color: '#F0F4FF', fontFamily: 'inherit', resize: 'vertical', minHeight: 100, outline: 'none', lineHeight: 1.6 }} />
              <div style={{ fontSize: 13, color: '#8B9ABF', margin: '20px 0 10px', fontWeight: 500 }}>Which category best describes this?</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {CATEGORIES.map(c => (
                  <button key={c} onClick={() => setCategory(category === c ? '' : c)} style={{ padding: '7px 14px', borderRadius: 99, border: `1px solid ${category === c ? 'rgba(0,212,255,0.5)' : '#263348'}`, background: category === c ? 'rgba(0,212,255,0.06)' : '#1A2438', fontSize: 13, color: category === c ? '#00D4FF' : '#8B9ABF', cursor: 'pointer', transition: 'all 0.2s' }}>{c}</button>
                ))}
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 32, paddingTop: 24, borderTop: '1px solid #1F2D45' }}>
                <button disabled style={{ padding: '10px 20px', background: 'transparent', border: '1px solid #263348', borderRadius: 8, color: '#4A5A7A', cursor: 'not-allowed', fontFamily: 'inherit', fontSize: 14, fontWeight: 700 }}>← Back</button>
                <button onClick={() => setStep(2)} style={{ padding: '12px 28px', background: '#00D4FF', border: 'none', borderRadius: 8, color: '#080C14', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 800 }}>Next →</button>
              </div>
            </div>
          )}

          {/* STEP 2 */}
          {status === 'form' && step === 2 && (
            <div style={{ padding: 40 }}>
              <div style={{ fontFamily: 'monospace', fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', color: '#00D4FF', marginBottom: 12 }}>Step 02 — The Trigger</div>
              <h2 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -0.8, lineHeight: 1.15, marginBottom: 8 }}>What kicks this<br />process off?</h2>
              <p style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 32, lineHeight: 1.6 }}>Every automation starts with a trigger event.</p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 10 }}>
                {TRIGGERS.map(t => (
                  <div key={t.label} onClick={() => setTrigger(t.label)} style={{ background: trigger === t.label ? 'rgba(0,212,255,0.06)' : '#1A2438', border: `1px solid ${trigger === t.label ? 'rgba(0,212,255,0.5)' : '#1F2D45'}`, borderRadius: 12, padding: '16px 14px', cursor: 'pointer', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, transition: 'all 0.2s', boxShadow: trigger === t.label ? '0 0 0 1px rgba(0,212,255,0.2)' : 'none' }}>
                    <span style={{ fontSize: 22 }}>{t.icon}</span>
                    <span style={{ fontSize: 12, fontWeight: 700, color: trigger === t.label ? '#00D4FF' : '#8B9ABF', lineHeight: 1.3 }}>{t.label}</span>
                  </div>
                ))}
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 32, paddingTop: 24, borderTop: '1px solid #1F2D45' }}>
                <button onClick={() => setStep(1)} style={{ padding: '10px 20px', background: 'transparent', border: '1px solid #263348', borderRadius: 8, color: '#8B9ABF', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 700 }}>← Back</button>
                <button onClick={() => setStep(3)} style={{ padding: '12px 28px', background: '#00D4FF', border: 'none', borderRadius: 8, color: '#080C14', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 800 }}>Next →</button>
              </div>
            </div>
          )}

          {/* STEP 3 */}
          {status === 'form' && step === 3 && (
            <div style={{ padding: 40 }}>
              <div style={{ fontFamily: 'monospace', fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', color: '#00D4FF', marginBottom: 12 }}>Step 03 — The Tools</div>
              <h2 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -0.8, lineHeight: 1.15, marginBottom: 8 }}>Which apps do<br />you already use?</h2>
              <p style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 32, lineHeight: 1.6 }}>Select all that apply. We'll wire your workflow around your existing stack.</p>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: 8 }}>
                {TOOLS.map(t => (
                  <div key={t} onClick={() => toggleTool(t)} style={{ background: tools.includes(t) ? 'rgba(0,212,255,0.06)' : '#1A2438', border: `1px solid ${tools.includes(t) ? 'rgba(0,212,255,0.5)' : '#1F2D45'}`, borderRadius: 8, padding: '12px 14px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 10, transition: 'all 0.2s' }}>
                    <div style={{ width: 16, height: 16, borderRadius: 4, border: `1.5px solid ${tools.includes(t) ? '#00D4FF' : '#263348'}`, background: tools.includes(t) ? '#00D4FF' : 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontSize: 10, color: '#080C14', fontWeight: 900 }}>{tools.includes(t) ? '✓' : ''}</div>
                    <span style={{ fontSize: 12, fontWeight: 700, color: tools.includes(t) ? '#00D4FF' : '#8B9ABF' }}>{t}</span>
                  </div>
                ))}
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 32, paddingTop: 24, borderTop: '1px solid #1F2D45' }}>
                <button onClick={() => setStep(2)} style={{ padding: '10px 20px', background: 'transparent', border: '1px solid #263348', borderRadius: 8, color: '#8B9ABF', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 700 }}>← Back</button>
                <button onClick={() => setStep(4)} style={{ padding: '12px 28px', background: '#00D4FF', border: 'none', borderRadius: 8, color: '#080C14', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 800 }}>Next →</button>
              </div>
            </div>
          )}

          {/* STEP 4 */}
          {status === 'form' && step === 4 && (
            <div style={{ padding: 40 }}>
              <div style={{ fontFamily: 'monospace', fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', color: '#00D4FF', marginBottom: 12 }}>Step 04 — The Outcome</div>
              <h2 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -0.8, lineHeight: 1.15, marginBottom: 8 }}>What should happen<br />at the end?</h2>
              <p style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 32, lineHeight: 1.6 }}>Describe the final result you want from this automation.</p>
              <textarea value={outcome} onChange={e => setOutcome(e.target.value)} placeholder="e.g. The lead should be added to HubSpot, receive a welcome email, and a follow-up task created in Notion..." style={{ width: '100%', background: '#1A2438', border: '1px solid #263348', borderRadius: 8, padding: '14px 16px', fontSize: 14, color: '#F0F4FF', fontFamily: 'inherit', resize: 'vertical', minHeight: 100, outline: 'none', lineHeight: 1.6 }} />
              <div style={{ fontSize: 13, color: '#8B9ABF', margin: '20px 0 10px', fontWeight: 500 }}>Quick-select common outcomes</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                {OUTCOMES.map(o => (
                  <button key={o} onClick={() => toggleOutcome(o)} style={{ padding: '7px 14px', borderRadius: 6, border: `1px solid ${outcomes.includes(o) ? 'rgba(0,212,255,0.5)' : '#263348'}`, background: outcomes.includes(o) ? 'rgba(0,212,255,0.06)' : '#1A2438', fontSize: 12, fontWeight: 700, color: outcomes.includes(o) ? '#00D4FF' : '#8B9ABF', cursor: 'pointer', transition: 'all 0.2s' }}>{o}</button>
                ))}
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 32, paddingTop: 24, borderTop: '1px solid #1F2D45' }}>
                <button onClick={() => setStep(3)} style={{ padding: '10px 20px', background: 'transparent', border: '1px solid #263348', borderRadius: 8, color: '#8B9ABF', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 700 }}>← Back</button>
                <button onClick={() => setStep(5)} style={{ padding: '12px 28px', background: '#00D4FF', border: 'none', borderRadius: 8, color: '#080C14', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 800 }}>Next →</button>
              </div>
            </div>
          )}

          {/* STEP 5 */}
          {status === 'form' && step === 5 && (
            <div style={{ padding: 40 }}>
              <div style={{ fontFamily: 'monospace', fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', color: '#00D4FF', marginBottom: 12 }}>Step 05 — Constraints</div>
              <h2 style={{ fontSize: 28, fontWeight: 900, letterSpacing: -0.8, lineHeight: 1.15, marginBottom: 8 }}>Any special rules<br />or edge cases?</h2>
              <p style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 32, lineHeight: 1.6 }}>Optional but helpful — error handling, business hours, conditional logic.</p>
              <textarea value={constraints} onChange={e => setConstraints(e.target.value)} placeholder="e.g. Only run during business hours. If email is missing, send a Slack alert instead..." style={{ width: '100%', background: '#1A2438', border: '1px solid #263348', borderRadius: 8, padding: '14px 16px', fontSize: 14, color: '#F0F4FF', fontFamily: 'inherit', resize: 'vertical', minHeight: 90, outline: 'none', lineHeight: 1.6 }} />
              <div style={{ marginTop: 24, padding: 24, background: '#1A2438', border: '1px solid #263348', borderRadius: 12 }}>
                <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 4 }}>Enter your email to generate your workflow</div>
                <div style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 13, color: '#8B9ABF', marginBottom: 14 }}>Free to download. No credit card needed. We'll also send you a copy.</div>
                <input type="email" value={email} onChange={e => { setEmail(e.target.value); setEmailError(false) }} placeholder="you@yourcompany.com" style={{ width: '100%', background: '#080C14', border: `1px solid ${emailError ? '#FF6B35' : '#263348'}`, borderRadius: 8, padding: '12px 16px', fontSize: 14, color: '#F0F4FF', fontFamily: 'inherit', outline: 'none' }} />
                {emailError && <div style={{ fontSize: 12, color: '#FF6B35', marginTop: 6 }}>Please enter a valid email address</div>}
              </div>
              <button onClick={generate} style={{ width: '100%', padding: 14, background: '#00D4FF', border: 'none', borderRadius: 8, fontFamily: 'inherit', fontSize: 16, fontWeight: 900, color: '#080C14', cursor: 'pointer', marginTop: 20, letterSpacing: -0.3 }}>
                Generate My Workflow →
              </button>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: 16 }}>
                <button onClick={() => setStep(4)} style={{ padding: '10px 20px', background: 'transparent', border: '1px solid #263348', borderRadius: 8, color: '#8B9ABF', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, fontWeight: 700 }}>← Back</button>
                <span style={{ fontFamily: 'monospace', fontSize: 11, color: '#4A5A7A' }}>Uses 1 credit</span>
              </div>
            </div>
          )}

          {/* LOADING */}
          {status === 'loading' && (
            <div style={{ padding: '60px 40px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
              <div style={{ width: 48, height: 48, borderRadius: '50%', border: '3px solid #1F2D45', borderTopColor: '#00D4FF', animation: 'spin 0.8s linear infinite', marginBottom: 24 }} />
              <div style={{ fontSize: 20, fontWeight: 900, letterSpacing: -0.5, marginBottom: 8 }}>Building your workflow...</div>
              <div style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 14, color: '#8B9ABF', marginBottom: 24 }}>Our AI is crafting your personalized n8n JSON</div>
              <div style={{ width: '100%', maxWidth: 300, display: 'flex', flexDirection: 'column', gap: 8 }}>
                {LOADING_STEPS.map((s, i) => (
                  <div key={s} style={{ fontFamily: 'monospace', fontSize: 11, padding: '6px 12px', borderRadius: 6, border: `1px solid ${i < loadingStep ? 'rgba(200,241,53,0.2)' : i === loadingStep ? 'rgba(0,212,255,0.3)' : '#1F2D45'}`, background: i < loadingStep ? 'rgba(200,241,53,0.05)' : i === loadingStep ? 'rgba(0,212,255,0.06)' : '#1A2438', color: i < loadingStep ? '#A8D020' : i === loadingStep ? '#00D4FF' : '#4A5A7A', transition: 'all 0.3s' }}>
                    {i < loadingStep ? '✓' : i === loadingStep ? '→' : '·'} {s}
                  </div>
                ))}
              </div>
              <style>{`@keyframes spin { to { transform: rotate(360deg) } }`}</style>
            </div>
          )}

          {/* SUCCESS */}
          {status === 'success' && (
            <div style={{ padding: '48px 40px', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' }}>
              <div style={{ width: 64, height: 64, borderRadius: '50%', background: 'rgba(200,241,53,0.1)', border: '1px solid rgba(200,241,53,0.3)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 28, marginBottom: 20 }}>⚡</div>
              <div style={{ fontSize: 24, fontWeight: 900, letterSpacing: -0.5, marginBottom: 8 }}>Your workflow is ready!</div>
              <div style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontSize: 15, color: '#8B9ABF', marginBottom: 28, maxWidth: 400 }}>Download and import directly into n8n to start automating.</div>
              <div style={{ width: '100%', background: '#080C14', border: '1px solid #1F2D45', borderRadius: 12, padding: 20, textAlign: 'left', overflow: 'auto', marginBottom: 20 }}>
                <pre style={{ fontFamily: 'monospace', fontSize: 12, color: '#00D4FF', lineHeight: 1.8, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                  {generatedJSON.length > 800 ? generatedJSON.substring(0, 800) + '\n\n  ... (download to see full workflow)' : generatedJSON}
                </pre>
              </div>
              <button onClick={download} style={{ width: '100%', padding: 14, background: '#C8F135', border: 'none', borderRadius: 8, fontFamily: 'inherit', fontSize: 15, fontWeight: 900, color: '#080C14', cursor: 'pointer', marginBottom: 12 }}>⬇ Download workflow.json</button>
              <div style={{ width: '100%', padding: '14px 20px', background: '#1A2438', border: '1px solid #1F2D45', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700, marginBottom: 2 }}>Don't have n8n yet?</div>
                  <div style={{ fontSize: 13, color: '#8B9ABF' }}>Sign up free and import your workflow in 2 minutes</div>
                </div>
                <button onClick={() => window.open('https://n8n.io/?ref=prompttoflow', '_blank')} style={{ padding: '8px 16px', background: 'transparent', border: '1px solid #00D4FF', borderRadius: 6, color: '#00D4FF', fontSize: 12, fontWeight: 800, cursor: 'pointer', whiteSpace: 'nowrap', fontFamily: 'inherit' }}>Get n8n Free →</button>
              </div>
              <div style={{ width: '100%', padding: '14px 20px', background: 'rgba(255,107,53,0.06)', border: '1px solid rgba(255,107,53,0.2)', borderRadius: 8, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700, color: '#FF6B35', marginBottom: 2 }}>Need help setting this up?</div>
                  <div style={{ fontSize: 12, color: '#8B9ABF' }}>I'll configure and deploy it for you — from $99</div>
                </div>
                <button style={{ padding: '8px 16px', background: '#FF6B35', border: 'none', borderRadius: 6, color: 'white', fontSize: 12, fontWeight: 800, cursor: 'pointer', whiteSpace: 'nowrap', fontFamily: 'inherit' }}>Book Setup →</button>
              </div>
            </div>
          )}

        </div>
      </div>

      {/* FOOTER */}
      <footer style={{ padding: '20px 40px', borderTop: '1px solid #1F2D45', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: '#0D1320' }}>
        <div style={{ fontWeight: 900, fontSize: 14, letterSpacing: -0.3 }}>Prompt<span style={{ color: '#00D4FF' }}>To</span>Flow</div>
        <div style={{ fontFamily: 'monospace', fontSize: 11, color: '#4A5A7A' }}>Free to generate · Yours to keep · No credit card needed</div>
      </footer>

    </div>
  )
}
